version: '4'
services:
  spatialone:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ${HOST_DATA_PATH}:/app/data
      #- shared-data:/app/data
    networks:
      - shared-network

  card:
    image: albertplaplanas/card-api:latest
    platform: linux/amd64
    volumes:
      - ${HOST_DATA_PATH}:/app/data
      #- shared-data:/app/data
    ports:
      - "81:80"
      # to reach the api from spatialone run curl http://card:80/test --noproxy "*"
    networks:
      - shared-network

  hovernet:
    build:
      context: ./models/hovernet
      dockerfile: Dockerfile_hovernet
    platform: linux/amd64
    volumes:
      - ${HOST_DATA_PATH}:/app/data
      #- shared-data:/app/data
    networks:
      - shared-network

volumes:
  shared-data:

networks:
  shared-network:
    driver: bridge
