version: 1
formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(filename)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s | %(levelname)s | %(filename)s | %(pathname)s | %(lineno)d | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

loggers:
  python_logger:
    level: INFO
    handlers: [console]
