ARG R_VERSION=4.3.1
FROM rocker/tidyverse:${R_VERSION}

#TODO are these needed for external users? probably not
ARG NO_PROXY
ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV NO_PROXY=${NO_PROXY}
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}

# setup system packages
RUN apt-get update && apt-get install -y \
        apt-utils libxt-dev libfontconfig1-dev libxml2-dev \
        gettext libmpfrc++-dev build-essential automake \
        pkg-config libtool g++ gfortran \
        libomp-dev libblas-dev liblapack-dev libatlas-base-dev \
        libudunits2-dev libssl-dev libgdal-dev libsodium-dev \
        libharfbuzz-dev libfribidi-dev libarmadillo-dev \
        libblosc-dev h5utils hdf5-helpers hdf5-tools \
        libcurl4-openssl-dev less vim mc wget

# setup working directory
WORKDIR /app
RUN mkdir cache/

COPY . .

# install CARD requirements
RUN Rscript -e "source('requirements.R')"
RUN echo "RETICULATE_AUTOCONFIGURE = FALSE" > ~/.Renviron

# Unset all proxy vars
ENV NO_PROXY=""
ENV HTTP_PROXY=""
ENV HTTPS_PROXY=""
ENV http_proxy=""
ENV https_proxy=""

# run api
CMD ["Rscript", "run.R"]